spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/luiza_labs_exam_db
    username: luiza_labs
    password: luizalabs
  jpa:
    hibernate.ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: luiza_labs_exam
  flyway:
    check-location: true
    enabled: true
    url: jdbc:postgresql://localhost:5432/luiza_labs_exam_db
    user: luiza_labs
    password: luizalabs
#logging:
#  level:
#    root: debug